/* tslint:disable */
/* eslint-disable */
/**
 * sero API
 * API of sero server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AuthToken
 */
export interface AuthToken {
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    'token'?: string;
}
/**
 * 
 * @export
 * @interface Details
 */
export interface Details {
    /**
     * 
     * @type {string}
     * @memberof Details
     */
    'details'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add origin
         * @param {string} xSubdomain 
         * @param {string} [origin] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCorsAddPost: async (xSubdomain: string, origin?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xSubdomain' is not null or undefined
            assertParamExists('apiCorsAddPost', 'xSubdomain', xSubdomain)
            const localVarPath = `/api/cors/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xSubdomain != null) {
                localVarHeaderParameter['X-Subdomain'] = String(xSubdomain);
            }


            if (origin !== undefined) { 
                localVarFormParams.set('origin', origin as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Clear related origins
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCorsClearPost: async (xSubdomain: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xSubdomain' is not null or undefined
            assertParamExists('apiCorsClearPost', 'xSubdomain', xSubdomain)
            const localVarPath = `/api/cors/clear`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xSubdomain != null) {
                localVarHeaderParameter['X-Subdomain'] = String(xSubdomain);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Enable site
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDisablePost: async (xSubdomain: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xSubdomain' is not null or undefined
            assertParamExists('apiDisablePost', 'xSubdomain', xSubdomain)
            const localVarPath = `/api/disable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xSubdomain != null) {
                localVarHeaderParameter['X-Subdomain'] = String(xSubdomain);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Download site as zip
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadPost: async (xSubdomain: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xSubdomain' is not null or undefined
            assertParamExists('apiDownloadPost', 'xSubdomain', xSubdomain)
            const localVarPath = `/api/download`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xSubdomain != null) {
                localVarHeaderParameter['X-Subdomain'] = String(xSubdomain);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Enable site
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEnablePost: async (xSubdomain: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xSubdomain' is not null or undefined
            assertParamExists('apiEnablePost', 'xSubdomain', xSubdomain)
            const localVarPath = `/api/enable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xSubdomain != null) {
                localVarHeaderParameter['X-Subdomain'] = String(xSubdomain);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Check that server is alive
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiHealthGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Authenticate user
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLoginPost: async (username?: string, password?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();


            if (username !== undefined) { 
                localVarFormParams.set('username', username as any);
            }
    
            if (password !== undefined) { 
                localVarFormParams.set('password', password as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register user
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiRegistrationPost: async (username?: string, password?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/registration`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();


            if (username !== undefined) { 
                localVarFormParams.set('username', username as any);
            }
    
            if (password !== undefined) { 
                localVarFormParams.set('password', password as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Enable site
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTeardownPost: async (xSubdomain: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xSubdomain' is not null or undefined
            assertParamExists('apiTeardownPost', 'xSubdomain', xSubdomain)
            const localVarPath = `/api/teardown`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xSubdomain != null) {
                localVarHeaderParameter['X-Subdomain'] = String(xSubdomain);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload site as zip
         * @param {string} xSubdomain 
         * @param {File} [archive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUploadPost: async (xSubdomain: string, archive?: File, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xSubdomain' is not null or undefined
            assertParamExists('apiUploadPost', 'xSubdomain', xSubdomain)
            const localVarPath = `/api/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xSubdomain != null) {
                localVarHeaderParameter['X-Subdomain'] = String(xSubdomain);
            }


            if (archive !== undefined) { 
                localVarFormParams.append('archive', archive as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add origin
         * @param {string} xSubdomain 
         * @param {string} [origin] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCorsAddPost(xSubdomain: string, origin?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCorsAddPost(xSubdomain, origin, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Clear related origins
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiCorsClearPost(xSubdomain: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiCorsClearPost(xSubdomain, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Enable site
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDisablePost(xSubdomain: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDisablePost(xSubdomain, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Download site as zip
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDownloadPost(xSubdomain: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDownloadPost(xSubdomain, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Enable site
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEnablePost(xSubdomain: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiEnablePost(xSubdomain, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Check that server is alive
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiHealthGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiHealthGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Authenticate user
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLoginPost(username?: string, password?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthToken>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiLoginPost(username, password, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Register user
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiRegistrationPost(username?: string, password?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiRegistrationPost(username, password, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Enable site
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTeardownPost(xSubdomain: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTeardownPost(xSubdomain, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Upload site as zip
         * @param {string} xSubdomain 
         * @param {File} [archive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUploadPost(xSubdomain: string, archive?: File, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUploadPost(xSubdomain, archive, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Add origin
         * @param {string} xSubdomain 
         * @param {string} [origin] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCorsAddPost(xSubdomain: string, origin?: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiCorsAddPost(xSubdomain, origin, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Clear related origins
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiCorsClearPost(xSubdomain: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiCorsClearPost(xSubdomain, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Enable site
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDisablePost(xSubdomain: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiDisablePost(xSubdomain, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Download site as zip
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDownloadPost(xSubdomain: string, options?: any): AxiosPromise<File> {
            return localVarFp.apiDownloadPost(xSubdomain, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Enable site
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEnablePost(xSubdomain: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiEnablePost(xSubdomain, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Check that server is alive
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiHealthGet(options?: any): AxiosPromise<void> {
            return localVarFp.apiHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Authenticate user
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLoginPost(username?: string, password?: string, options?: any): AxiosPromise<AuthToken> {
            return localVarFp.apiLoginPost(username, password, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register user
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiRegistrationPost(username?: string, password?: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiRegistrationPost(username, password, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Enable site
         * @param {string} xSubdomain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTeardownPost(xSubdomain: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiTeardownPost(xSubdomain, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload site as zip
         * @param {string} xSubdomain 
         * @param {File} [archive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUploadPost(xSubdomain: string, archive?: File, options?: any): AxiosPromise<void> {
            return localVarFp.apiUploadPost(xSubdomain, archive, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Add origin
     * @param {string} xSubdomain 
     * @param {string} [origin] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiCorsAddPost(xSubdomain: string, origin?: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiCorsAddPost(xSubdomain, origin, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Clear related origins
     * @param {string} xSubdomain 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiCorsClearPost(xSubdomain: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiCorsClearPost(xSubdomain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Enable site
     * @param {string} xSubdomain 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiDisablePost(xSubdomain: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiDisablePost(xSubdomain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Download site as zip
     * @param {string} xSubdomain 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiDownloadPost(xSubdomain: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiDownloadPost(xSubdomain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Enable site
     * @param {string} xSubdomain 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiEnablePost(xSubdomain: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiEnablePost(xSubdomain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Check that server is alive
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiHealthGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Authenticate user
     * @param {string} [username] 
     * @param {string} [password] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiLoginPost(username?: string, password?: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiLoginPost(username, password, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register user
     * @param {string} [username] 
     * @param {string} [password] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiRegistrationPost(username?: string, password?: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiRegistrationPost(username, password, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Enable site
     * @param {string} xSubdomain 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiTeardownPost(xSubdomain: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiTeardownPost(xSubdomain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload site as zip
     * @param {string} xSubdomain 
     * @param {File} [archive] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiUploadPost(xSubdomain: string, archive?: File, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiUploadPost(xSubdomain, archive, options).then((request) => request(this.axios, this.basePath));
    }
}



