name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: "write"

jobs:
  create-tag-and-release:
    name: Create git tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.G_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install `toml` module
        run: |
          python -m pip install toml

      - name: Get tag from pyproject.toml
        id: get-tag
        shell: bash
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          echo PKG_VERSION=$VERSION >> $GITHUB_ENV

      - name: Set git tag
        shell: bash
        run: |
          git tag v${{ env.PKG_VERSION }}
          git push origin v${{ env.PKG_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl

  publish-to-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install

      - name: Publish package to PyPI
        run: |
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
